# Generated by Django 4.2.1 on 2023-05-10 17:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='completed',
        ),
    ]
